export const metadata = {
  title: 'Next.js Course',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{backgroundColor:"lightyellow", padding:"1rem",
           textAlign:"center", alignItems:"center" }}>
        <h1>HEADER</h1>
        </header>
        
        {children}
        
        <footer  style={{backgroundColor:"lightblue", padding:"1rem", 
          textAlign:"center", alignItems:"center" }}>
        <h1>FOOTER</h1>

        </footer>
        </body>

    </html>
  )
}
